version = 1
exclude_patterns = []
test_patterns = []

[[analyzers]]
  name = "docker"
  enabled = true

  [analyzers.meta]
    dockerfile_paths = ""

[[analyzers]]
  name = "python"
  enabled = true

  [analyzers.meta]
    runtime_version = "3.x.x"

[[analyzers]]
  name = "test-coverage"
  enabled = true

[[transformers]]
  name = "isort"
  enabled = true

[[transformers]]
  name = "black"
  enabled = true

[[transformers]]
  name = "ruff"
  enabled = true
