name: DeepSource

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov deepsource

      - name: Run tests with coverage
        run: pytest --cov=arbit --cov-report=xml

      - name: Report coverage to DeepSource
        run: deepsource report --analyzer test-coverage --key python --value-file coverage.xml
